#include "Include/stm32f401xe.h"
#include "stm32.h"

int main()
{
	/*
	• PA15: JTDI in pull-up
	• PA14: JTCK/SWCLK in pull-down
	• PA13: JTMS/SWDAT in pull-up
	• PB4: NJTRST in pull-up
	• PB3: JTDO in floating state
	*/
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN;
	GPIOA->MODER &= (GPIO_MODER_MODE0
		| GPIO_MODER_MODE1_0
		| GPIO_MODER_MODE2_0
		| GPIO_MODER_MODE3_0
		| GPIO_MODER_MODE4_0
		| GPIO_MODER_MODE5_0
		| GPIO_MODER_MODE6_0
		| GPIO_MODER_MODE7_0
		| GPIO_MODER_MODE8_0
		| GPIO_MODER_MODE9_0
		| GPIO_MODER_MODE10_0
		| GPIO_MODER_MODE11_0
		| GPIO_MODER_MODE12_0
		| GPIO_MODER_MODE13_0
		| GPIO_MODER_MODE14_0
		| GPIO_MODER_MODE15_0);

	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT0
		| GPIO_OTYPER_OT1
		| GPIO_OTYPER_OT2
		| GPIO_OTYPER_OT3
		| GPIO_OTYPER_OT4
		| GPIO_OTYPER_OT5
		| GPIO_OTYPER_OT6
		| GPIO_OTYPER_OT7
		| GPIO_OTYPER_OT8
		| GPIO_OTYPER_OT9
		| GPIO_OTYPER_OT10
		| GPIO_OTYPER_OT11
		| GPIO_OTYPER_OT12
		| GPIO_OTYPER_OT13
		| GPIO_OTYPER_OT14
		| GPIO_OTYPER_OT15);

	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPD0
		| GPIO_PUPDR_PUPD1
		| GPIO_PUPDR_PUPD2
		| GPIO_PUPDR_PUPD3
		| GPIO_PUPDR_PUPD4
		| GPIO_PUPDR_PUPD5
		| GPIO_PUPDR_PUPD6
		| GPIO_PUPDR_PUPD7
		| GPIO_PUPDR_PUPD8
		| GPIO_PUPDR_PUPD9
		| GPIO_PUPDR_PUPD10
		| GPIO_PUPDR_PUPD11
		| GPIO_PUPDR_PUPD12
		| GPIO_PUPDR_PUPD13
		| GPIO_PUPDR_PUPD14
		| GPIO_PUPDR_PUPD15);
	while(1)
	{
		;
	}
}
